export const INVALID_EMAIL = 'Email is invalid'
export const INVALID_PASSWORD = 'Password is invalid'
export const INVALID_USERNAME = 'Username is invalid'
export const USER_NOT_FOUND = 'User not found'
export const INVALID_PHONE_NUMBER = 'Phone number is invalid'
export const INVALID_URL = 'URL is invalid'
